import { program } from "commander";
import chalk from "chalk";
import ora from "ora";
import { analyzeRepo } from "./analyzer.js";
import { generateRoast } from "./roaster.js";

const BANNER = `
  ╔═══════════════════════════════════════════════╗
  ║                                               ║
  ║   📋  G I T — R O A S T  📋                  ║
  ║                                               ║
  ║   The performance review your git             ║
  ║   history didn't ask for.                     ║
  ║                                               ║
  ╚═══════════════════════════════════════════════╝
`;

program
  .name("git-roast")
  .version("1.0.0")
  .description(
    "A sarcastic performance review generated from your actual git history 📋"
  )
  .addHelpText(
    "after",
    `
  Examples:
    $ cd my-project && git-roast
    $ git-roast --path /path/to/repo

  Run it on any git repo. No API keys. No signup.
  Just your commits and the cold, hard truth.
  `
  );

program
  .option("-p, --path <path>", "Path to git repo (defaults to current directory)")
  .action(async (opts: { path?: string }) => {
    console.log(chalk.red.bold(BANNER));

    if (opts.path) {
      process.chdir(opts.path);
    }

    const spinner = ora({
      text: chalk.dim("  Reading your git history... this might be painful."),
      spinner: "dots",
    }).start();

    await sleep(800);

    let stats;
    try {
      stats = analyzeRepo();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      spinner.fail(chalk.red(`  ${msg}`));
      process.exit(1);
    }

    spinner.text = chalk.dim("  Analyzing your life choices...");
    await sleep(600);

    spinner.text = chalk.dim("  Preparing your roast...");
    await sleep(600);

    spinner.succeed(chalk.green("  Analysis complete. Brace yourself.\n"));
    await sleep(300);

    const sections = generateRoast(stats);

    for (const section of sections) {
      // Section header
      console.log(
        chalk.bold.red(`  ═══ ${section.title} ${"═".repeat(Math.max(0, 45 - section.title.length))}`)
      );
      console.log("");

      for (const line of section.lines) {
        // Stats lines (contain numbers/colons)
        if (line.match(/^(Total|Average|Active|Lines|Most|Net|Peak|Longest|Weekend|Late|Friday|Stale|Current|Biggest|Commits|Shortest|WIP|One-word)/)) {
          console.log(chalk.white(`  ${line}`));
        } else if (line.startsWith("  ") && (line.includes("x  ") || line.includes("- "))) {
          // File list or branch list
          console.log(chalk.dim(`  ${line}`));
        } else if (line.includes("Performance Score")) {
          // Score line
          const [before, after] = line.split(/[█░]+/);
          const barMatch = line.match(/[█░]+/);
          const bar = barMatch ? barMatch[0] : "";
          const filledCount = (bar.match(/█/g) || []).length;
          const barColor = filledCount >= 7 ? chalk.green : filledCount >= 5 ? chalk.yellow : chalk.red;
          console.log(`${chalk.white(before)}${barColor(bar)}${chalk.white(after || "")}`);
        } else if (line === "") {
          console.log("");
        } else {
          // Roast lines
          console.log(chalk.yellow(`  ${line}`));
        }
      }
      console.log("");
    }

    // Footer
    console.log(chalk.dim("  ─────────────────────────────────────────────────"));
    console.log(chalk.dim("  Generated by git-roast | Your commits. Your consequences."));
    console.log(chalk.dim("  github.com/carsonlabs/git-roast\n"));
  });

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

program.parse();
